# Goal: build a dummy cicd pipeline 

name: CICD

on:
  workflow_dispatch: 

  
jobs:
   # CI
  code:
      runs-on: ubuntu-latest
      steps:
       - name: devloper will write the code
         run: echo "code is written"
          
          
  build:
      needs: code
      runs-on: ubuntu-latest
      steps:
        - name: build the code
          run: echo "code is successfully build"
          
  test:
      needs: build
      runs-on: ubuntu-latest
      steps:
       - name: testing should be done 
         run: echo "test is successfully done "
     # CD     
  deploy:
      needs: [code,build,test]
      runs-on: ubuntu-latest
      steps:
         - name: deploy it to the server
           run: echo "successfully deployed"
          
     
