name: EC2 DAST Security Scan

on:
  # Triggers can be called by your workflow
  workflow_call: 

jobs:
  dast_scan:
    name: Run DAST on Self-Hosted EC2
    # Specifies that this job MUST run on your AWS EC2 self-hosted runner
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
     
      - name: Wait for services to be healthy
        run: |
           timeout 900s sh -c 'until curl -s http://${{ secrets.EC2_HOST }} > /dev/null; do sleep 2; done'

            # Scan the running application 
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://${{ secrets.EC2_HOST }}'
          fail_action: false
          allow_issue_writing: false
        

      - name: Upload Scan Report
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: ec2-zap-dast-report
          path: zap_report.html
