# goaL

name: devSecops pipeline

on:
  push:

jobs:

  # Secret Scan
  secret-scan:
    secrets: inherit
    uses: ./.github/workflows/secret-scan.yml

  #code
  code:
    needs: secret-scan
    uses: ./.github/workflows/lint-and-test-and-matrix-concept.yml

  #sonar scan for the SAST

  sonar-scan:
    needs: code
    secrets: inherit
    uses: ./.github/workflows/sonar-scan.yml

  dependency-scan:
    needs: sonar-scan
    uses: ./.github/workflows/dependency-scan.yml

  build-the-docker-image-then-scan-with-trivy:
    needs: dependency-scan
    secrets: inherit
    uses: ./.github/workflows/trivy-scans.yml


