# goaL

name: devSecops pipeline

on:
  push:

jobs:

  # Secret Scan
  secret-scan:
    secrets: inherit
    uses: ./.github/workflows/secret-scan.yml

  #code
  code:
    needs: secret-scan
    uses: ./.github/workflows/lint-and-test-and-matrix-concept.yml

  #sonar scan for the SAST

  sonar-scan:
    needs: code
    secrets: inherit
    uses: ./.github/workflows/sonar-scan.yml

# scan the dependency before installing the packages
  dependency-scan:
    needs: sonar-scan
    uses: ./.github/workflows/dependency-scan.yml

#  build-the-docker-image-then-scan-with-trivy-and-push-the-image-to-dockerhub

  build-the-docker-image-then-scan-with-trivy-and-push-the-image-to-dockerhub:
    needs: dependency-scan
    secrets: inherit
    uses: ./.github/workflows/trivy-scans.yml

# Deploy to the self-hosted runner use self-host as a runner in deploy.yml
 
  deploy:
    needs: build-the-docker-image-then-scan-with-trivy-and-push-the-image-to-dockerhub
    uses:  ./.github/workflows/Deploy.yml

  DAST:
    needs: deploy
    uses: ./.github/workflows/DAST.yml
    secrets: inherit

