# Goal i will pass the env variable and use it in jobs 

#name of the workflow
name: secrets of docker are stored

on:
  workflow_dispatch: 

# This is an 2 environment variable that i can use anywhere only in this yml script 
env:
  NAME: UDIT
  MID_NAME: RAJ
  
jobs:
# Name of the job
  docker-passwd:
    runs-on: ubuntu-latest
    steps:
      - name: use the env varaible
      # environment variable is used
        run: echo " my nam is ${{ env.NAME }} ${{ env.MID_NAME }} "

# the secret is used which we have created in github secrets and variable and this is an repository secret it can be used anywhere in the repository and any workflow in the repository.
# but we can nit use these secrets outside this repository
      - name: secrets of my docker 
        run: echo " my password of dockerhub is ${{secrets.UDIT_DOCKER_PASSWORD}}"
    
    
  

    
