# Goal: To Scan the code for the tokens . secrets , api keys , or any secrets leaked and if we found that
# so we can quickly rotate the exposed tokes/keys 

name: secrets scan

on: 
  push:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history, from the first commit that is created 

      - name: Run Betterleaks Action it is better than gitleaks 
        uses: dortort/betterleaks-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: /demo-github-actions/.betterleaks.toml