# Goal i will pass the env variable and use it in jobs 

name: secrets of docker are stored

on:
  push: 

env:
  NAME: UDIT
  MID_NAME: RAJ
jobs:
  docker-passwd:
    runs-on: ubuntu-latest
    steps:
      - name: use the env varaible
        run: echo " my nam is ${{ env.NAME }} ${{ env.MID_NAME }} "
      - name: secrets of my docker
        run: " my password of dockerhub is {{}}"
    
    
  

    
