#Goal - To say hello and print title name 

name: OKkkk

on:
  workflow_dispatch:

jobs:

   greet:
      runs-on: ubuntu-latest
      steps:
        - name: say okk 
          run: echo "Hello  okk"
  repo-name:
      runs-on: ubuntu-latest
      steps:
        - name: Print repo name only
          run: echo "The repo name is ${{ github.event.repository.name }}"

